package traffic

import (
	"fmt"
	"sort"
	"strings"

	"github.com/villadalmine/kgraph/internal/graph"
	"sigs.k8s.io/yaml"
)

// metaLabelPrefixes are pod-identity labels useless as policy selectors.
var metaLabelPrefixes = []string{
	"io.kubernetes.", "io.cilium.", "pod-template-hash", "controller-revision-hash",
	"statefulset.kubernetes.io", "apps.kubernetes.io",
}

// peer is one observed allowed source toward a destination workload.
type peer struct {
	labels map[string]string
	ns     string
	proto  string
	port   string
}

// SuggestPolicies generates least-privilege policies (kind: "k8s" or "cilium")
// that allow exactly the observed in-cluster ingress per in-namespace workload.
// The result is multi-document YAML; applying it makes the namespace default-deny
// for the covered workloads.
func SuggestPolicies(g *graph.Graph, ns, kind string) ([]byte, error) {
	// Collect, per destination node, the set of allowed in-cluster sources.
	dests := map[string][]peer{}
	var skipped []string

	for _, e := range g.Edges {
		if e.Kind != graph.RelFlow || e.Dropped {
			continue
		}
		dst := g.Nodes[e.To]
		src := g.Nodes[e.From]
		if dst == nil || src == nil || dst.Namespace != ns || dst.Kind == "External" {
			continue
		}
		if src.Kind == "External" {
			skipped = append(skipped, fmt.Sprintf("%s <- %s (external; add an ipBlock/toFQDNs rule manually)", dst.Name, src.Name))
			continue
		}
		proto, port := parsePort(e.Note)
		dests[dst.ID] = append(dests[dst.ID], peer{labels: cleanLabels(src.Labels), ns: src.Namespace, proto: proto, port: port})
	}

	var docs []string
	var ids []string
	for id := range dests {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	for _, id := range ids {
		dst := g.Nodes[id]
		sel := cleanLabels(dst.Labels)
		if len(sel) == 0 {
			skipped = append(skipped, dst.Name+" (no usable selector labels)")
			continue
		}
		var doc map[string]interface{}
		if kind == "cilium" {
			doc = ciliumPolicy(ns, dst.Name, sel, dests[id])
		} else {
			doc = k8sPolicy(ns, dst.Name, sel, dests[id])
		}
		y, err := yaml.Marshal(doc)
		if err != nil {
			return nil, err
		}
		docs = append(docs, string(y))
	}

	var b strings.Builder
	b.WriteString("# Generated by kgraph from observed Hubble flows — review before applying.\n")
	b.WriteString("# Applying these makes the listed workloads default-deny for ingress.\n")
	for _, s := range dedupStr(skipped) {
		b.WriteString("# skipped: " + s + "\n")
	}
	b.WriteString("\n")
	b.WriteString(strings.Join(docs, "---\n"))
	return []byte(b.String()), nil
}

func k8sPolicy(ns, name string, sel map[string]string, peers []peer) map[string]interface{} {
	var ingress []interface{}
	for _, p := range peers {
		from := map[string]interface{}{"podSelector": map[string]interface{}{"matchLabels": p.labels}}
		if p.ns != "" && p.ns != ns {
			from["namespaceSelector"] = map[string]interface{}{
				"matchLabels": map[string]interface{}{"kubernetes.io/metadata.name": p.ns},
			}
		}
		rule := map[string]interface{}{"from": []interface{}{from}}
		if p.port != "" {
			rule["ports"] = []interface{}{map[string]interface{}{"protocol": p.proto, "port": atoiAny(p.port)}}
		}
		ingress = append(ingress, rule)
	}
	return map[string]interface{}{
		"apiVersion": "networking.k8s.io/v1",
		"kind":       "NetworkPolicy",
		"metadata":   map[string]interface{}{"name": "allow-observed-" + name, "namespace": ns},
		"spec": map[string]interface{}{
			"podSelector": map[string]interface{}{"matchLabels": sel},
			"policyTypes": []interface{}{"Ingress"},
			"ingress":     ingress,
		},
	}
}

func ciliumPolicy(ns, name string, sel map[string]string, peers []peer) map[string]interface{} {
	var ingress []interface{}
	for _, p := range peers {
		ml := map[string]interface{}{}
		for k, v := range p.labels {
			ml[k] = v
		}
		if p.ns != "" {
			ml["k8s:io.kubernetes.pod.namespace"] = p.ns
		}
		rule := map[string]interface{}{"fromEndpoints": []interface{}{map[string]interface{}{"matchLabels": ml}}}
		if p.port != "" {
			rule["toPorts"] = []interface{}{map[string]interface{}{
				"ports": []interface{}{map[string]interface{}{"port": p.port, "protocol": p.proto}},
			}}
		}
		ingress = append(ingress, rule)
	}
	return map[string]interface{}{
		"apiVersion": "cilium.io/v2",
		"kind":       "CiliumNetworkPolicy",
		"metadata":   map[string]interface{}{"name": "allow-observed-" + name, "namespace": ns},
		"spec": map[string]interface{}{
			"endpointSelector": map[string]interface{}{"matchLabels": sel},
			"ingress":          ingress,
		},
	}
}

// cleanLabels drops pod-identity meta labels, leaving app-level selectors.
func cleanLabels(in map[string]string) map[string]string {
	out := map[string]string{}
	for k, v := range in {
		meta := false
		for _, p := range metaLabelPrefixes {
			if strings.HasPrefix(k, p) {
				meta = true
				break
			}
		}
		if !meta {
			out[k] = v
		}
	}
	return out
}

func parsePort(note string) (proto, port string) {
	for _, f := range strings.Fields(note) {
		if i := strings.IndexByte(f, ':'); i > 0 {
			return f[:i], f[i+1:]
		}
	}
	return "TCP", ""
}

func atoiAny(s string) interface{} {
	n := 0
	for _, r := range s {
		if r < '0' || r > '9' {
			return s
		}
		n = n*10 + int(r-'0')
	}
	return n
}

func dedupStr(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}
