// Package docs renders a Markdown page documenting a scope (namespace or
// cluster) with embedded per-layer diagrams, for committing as docs-as-code.
package docs

import (
	"fmt"
	"strings"
	"time"
)

// Section is one abstraction layer with its embedded diagram.
type Section struct {
	Name  string
	Desc  string
	Count int
	Nodes int    // nodes in the rendered subgraph
	Image string // relative path to the SVG, empty if not rendered
}

// KindCount is an inventory row.
type KindCount struct {
	Kind  string
	Count int
}

// Security is the policy-coverage posture for a namespace, mapped from
// traffic.Summary at the CLI boundary (keeps this package decoupled from
// traffic). See specs/0004-autodoc-traffic-security.md.
type Security struct {
	Policies    int
	DeniedFlows int
	GapFlows    int
	Unprotected []string // in-namespace workloads selected by no policy
}

// Page is everything needed to render the Markdown document.
type Page struct {
	Title        string   // e.g. "Namespace: monitoring"
	ObjectCount  int      // raw objects collected
	GraphNodes   int      // nodes after pruning
	Overview     string   // optional AI-generated narrative (Markdown)
	Architecture *Section // optional whole-namespace overview diagram, rendered first
	Sections     []Section
	Traffic      *Section  // optional observed-traffic diagram (Hubble)
	TrafficNote  string    // shown when traffic was requested but unavailable
	Security     *Security // optional policy-coverage posture
	Inventory    []KindCount
	Generated    time.Time
}

// Markdown renders the page to a Markdown string.
func Markdown(p Page) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s\n\n", p.Title)
	fmt.Fprintf(&b, "> Generated by [kgraph](https://github.com/villadalmine/kgraph) on %s.\n\n",
		p.Generated.Format("2006-01-02 15:04"))
	fmt.Fprintf(&b, "%d objects collected · %d shown in diagrams (noise pruned).\n\n",
		p.ObjectCount, p.GraphNodes)

	if strings.TrimSpace(p.Overview) != "" {
		b.WriteString("## Overview\n\n")
		b.WriteString(strings.TrimSpace(p.Overview))
		b.WriteString("\n\n")
	}

	if p.Architecture != nil {
		a := p.Architecture
		b.WriteString("## Architecture\n\n")
		fmt.Fprintf(&b, "Whole-namespace map — %d resources shown.\n\n", a.Nodes)
		if a.Image != "" {
			fmt.Fprintf(&b, "![architecture diagram](%s)\n\n", a.Image)
		}
	}

	if len(p.Sections) > 0 {
		// Sections are pre-ordered by significance tier (see layers.Rank).
		b.WriteString("## Layers\n\n")
		b.WriteString("| Layer | Resources | Diagram | Description |\n")
		b.WriteString("|---|---:|:--:|---|\n")
		folded := false
		for _, s := range p.Sections {
			if s.Image != "" {
				fmt.Fprintf(&b, "| [%s](#%s) | %d | ✓ | %s |\n", s.Name, anchor(s.Name), s.Count, s.Desc)
			} else {
				fmt.Fprintf(&b, "| %s | %d | – | %s |\n", s.Name, s.Count, s.Desc)
				folded = true
			}
		}
		b.WriteString("\n")
		if folded {
			b.WriteString("_Layers marked “–” are small and shown within the Architecture overview above._\n\n")
		}

		for _, s := range p.Sections {
			if s.Image == "" {
				continue // small layer: table mention only, no standalone diagram
			}
			fmt.Fprintf(&b, "## %s\n\n", s.Name)
			fmt.Fprintf(&b, "%s — %d resources.\n\n", s.Desc, s.Count)
			fmt.Fprintf(&b, "![%s diagram](%s)\n\n", s.Name, s.Image)
		}
	}

	if p.Traffic != nil || strings.TrimSpace(p.TrafficNote) != "" {
		b.WriteString("## Observed traffic\n\n")
		if p.Traffic != nil {
			fmt.Fprintf(&b, "Network flows observed via Cilium Hubble — %d nodes.\n\n", p.Traffic.Nodes)
			if p.Traffic.Image != "" {
				fmt.Fprintf(&b, "![observed traffic](%s)\n\n", p.Traffic.Image)
			}
		} else {
			fmt.Fprintf(&b, "_%s_\n\n", strings.TrimSpace(p.TrafficNote))
		}
	}

	if p.Security != nil {
		s := p.Security
		b.WriteString("## Security posture\n\n")
		fmt.Fprintf(&b, "Policy coverage from NetworkPolicy / CiliumNetworkPolicy.\n\n")
		fmt.Fprintf(&b, "| Metric | Value |\n|---|---:|\n")
		fmt.Fprintf(&b, "| Policies in effect | %d |\n", s.Policies)
		fmt.Fprintf(&b, "| Denied flows | %d |\n", s.DeniedFlows)
		fmt.Fprintf(&b, "| Gap flows (allowed → unprotected) | %d |\n", s.GapFlows)
		fmt.Fprintf(&b, "| Unprotected workloads | %d |\n\n", len(s.Unprotected))
		if len(s.Unprotected) == 0 {
			b.WriteString("All observed workloads are selected by at least one policy. ✅\n\n")
		} else {
			b.WriteString("Workloads selected by **no** policy (wide open):\n\n")
			for _, w := range s.Unprotected {
				fmt.Fprintf(&b, "- `%s`\n", w)
			}
			b.WriteString("\n")
		}
	}

	if len(p.Inventory) > 0 {
		b.WriteString("## Inventory\n\n")
		b.WriteString("| Kind | Count |\n")
		b.WriteString("|---|---:|\n")
		for _, kc := range p.Inventory {
			fmt.Fprintf(&b, "| %s | %d |\n", kc.Kind, kc.Count)
		}
		b.WriteString("\n")
	}

	return b.String()
}

// anchor builds a GitHub-style heading anchor.
func anchor(s string) string {
	return strings.ToLower(strings.ReplaceAll(s, " ", "-"))
}
